### ISSUE TITLE
Problems building the visual

### ISSUE THREAD

**Issue by erapade** [microsoft/PowerBI-visuals-TextFilter#25]
This is closely related to #21. Our customers can't wait so we decided to do the modifications ourself. We then have two problems. As they might be connected I only create one issue

1. The source code is not possible to build since things are missing or wrong
2. When fixing the problems above (at least as we think), the visual did not interact as a filter in Power BI

### We start with (1), the problem to build the code
**1) Build tools was already installed**

**2) Downloaded the latest version from GitHub**
I then also changed the visual guid

**3) npm install**
This created the node_modules folder

**4) pbiviz package**
 This generated this output:
info   Compile C:\Users\ds82395\Downloads\PowerBI-visuals-TextFilter\.tmp\precompile\visualPlugin.ts
Error parsing bundle asset "C:\Users\ds82395\Downloads\PowerBI-visuals-TextFilter\.tmp\drop\visual.js": no such file
No bundles were parsed. Analyzer will show only original module sizes from stats file.
Webpack Bundle Analyzer saved report to C:\Users\ds82395\Downloads\PowerBI-visuals-TextFilter\webpack.statistics.prod.html
ERROR  Failed to compile with 1 errors                                                                   13:58:45
This dependency was not found:
Globalize in ./.tmp/build/visual.js
To install it, you can run: npm install --save Globalize

**5) executed:  npm install --save globalize**
added 2 packages, and audited 11 packages in 1s

**6) pbiviz package again**
info   Start packaging...
warn   No such file or directory: C:\Users\ds82395\Downloads\PowerBI-visuals-TextFilter\dependencies.json
error  should be object 
error  Invalid dependencies

**7) Added an empty dependencies.json file according to below**
{ "dependencies" :
    {}
  }

**8) pbiviz package again. But this time it looks ok to me and a got a package generated**
 info   Building visual...
 warn   For better development experience, we strongly recommend converting the visual to es2015 modules
 warn   https://microsoft.github.io/PowerBI-visuals/docs/latest/how-to-guide/migrating-to-powerbi-visuals-tools-3-0
 info   Compile .api/v1.11.0/PowerBI-visuals.d.ts
 info   Compile node_modules/powerbi-models/dist/models-noexports.d.ts
 info   Compile node_modules/powerbi-visuals-utils-dataviewutils/lib/index.d.ts
 info   Compile node_modules/powerbi-visuals-utils-typeutils/lib/index.d.ts
 info   Compile node_modules/powerbi-visuals-utils-svgutils/lib/index.d.ts
 info   Compile node_modules/powerbi-visuals-utils-interactivityutils/lib/index.d.ts
 info   Compile src/visual.ts
 info   Compile C:\Users\ds82395\Downloads\PowerBI-visuals-TextFilter\.tmp\precompile\visualPlugin.ts
 info   Start packaging...
 info   Package compression enabled
 info   Package created!
 info   Finish packaging
Webpack Bundle Analyzer saved report to C:\Users\ds82395\Downloads\PowerBI-visuals-TextFilter\webpack.statistics.prod.html
 DONE  Compiled successfully in 1765ms                                                                    14:09:46
 warn   Please, make sure that the visual source code matches to requirements of certification:
 info   Visual must use API v2.5 and above
 info   The project repository must:
 info   Include package.json and package-lock.json;
 info   Not include node_modules folder
 info   Run npm install expect no errors
 info   Run pbiviz package expect no errors
 info   The compiled package of the Custom Visual should match submitted package.
 info   npm audit command must not return any alerts with high or moderate level.
 info   The project must include Tslint from Microsoft with no overridden configuration, and this command shouldn’t return any tslint errors.
 info   https://www.npmjs.com/package/tslint-microsoft-contrib
 info   Ensure no arbitrary/dynamic code is run (bad: eval(), unsafe use of settimeout(), requestAnimationFrame(), setinterval(some function with user input).. running user input/data etc.)
 info   Ensure DOM is manipulated safely (bad: innerHTML, D3.html(<some user/data input>), unsanitized user input/data directly added to DOM, etc.)
 info   Ensure no js errors/exceptions in browser console for any input data. As test dataset please use this sample report
 info   Full description of certification requirements you can find in documentation:
 info   https://docs.microsoft.com/en-us/power-bi/power-bi-custom-visuals-certified#certification-requirements

### Then we jump into issue 2, that the visual doesn't filter
So I start with the newly built filter from above
**1) Imported the visual into a simple test Power BI file that already contains the official version of the text earch filter**
**2) Replaced the official filter with my newly built filter**
But now the filter doesn't filter. I can see that it reads the maximum 30'000 rows, but it does not filter other tables in the canvas
And now I have two (since I changed the visual Guid). But it's only the original text search visual that filters. Switching to the new does not show anything

**Comment by stopyoukid** [comment]
I think the main issue is that `pbiviz` is packaging the visually slightly differently than when it was originally developed, and so that affected how it loaded the filtering library.

To fix your issue, I added a new branch [build-fix](https://github.com/microsoft/PowerBI-visuals-TextFilter/tree/build-fix), which should get you running.  You'll need to update the guid again like you did before, but it should filter.

**Comment by erapade** [comment]
Sorry @stopyoukid. I will try to close this now

**Comment by erapade** [comment]
Closing since the problem is resolved

**Comment by stopyoukid** [comment]
Oh, just saw your comment, so it is resolved then?
